/** autogenerated. shouldn't be edited, but part of version control! */

import * as $s0 from "ixalan/responses/static.ts";
import * as $p0 from "app/routes/pokemon/:pokemon/page.tsx";
import * as $p1 from "app/routes/pokemon/page.tsx";
import * as $p2 from "app/routes/leaderboard/page.tsx";
import * as $p3 from "app/routes/me/page.tsx";
import * as $h0 from "app/routes/api/auth/signout/handler.ts";
import * as $h1 from "app/routes/api/auth/signin/handler.ts";
import * as $h2 from "app/routes/api/auth/callback/handler.ts";
import * as $h3 from "app/routes/api/pokemon/:pokemon/handler.ts";
import * as $h4 from "app/routes/api/pokemon/handler.ts";
import * as $h5 from "app/routes/api/search/handler.ts";
import * as $p4 from "app/routes/page.tsx";

const manifest = {
  "/static/*": { static: $s0 },
  "/pokemon/:pokemon": { page: $p0 },
  "/pokemon": { page: $p1 },
  "/leaderboard": { page: $p2 },
  "/me": { page: $p3 },
  "/api/auth/signout": { handler: $h0 },
  "/api/auth/signin": { handler: $h1 },
  "/api/auth/callback": { handler: $h2 },
  "/api/pokemon/:pokemon": { handler: $h3 },
  "/api/pokemon": { handler: $h4 },
  "/api/search": { handler: $h5 },
  "/": { page: $p4 },
} as const;

export default manifest;
export type Manifest = typeof manifest;
